version: "3"

services:
 jobportal:
    container_name: job
    image: "job-portal-api"
    ports: 
      - "8080:8080"
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .job.postgres.env
      - .auth.env
      - .redis.env
    depends_on:
      - postgres
    restart: always
 postgres:
    container_name: postgres
    image: postgres
    ports: 
       - "5432:5432"
    env_file:
       - .postgres.env
 redis:
    container_name: redis
    image: redis
    ports: 
       - "6379:6379"
