// Code generated by MockGen. DO NOT EDIT.
// Source: jobRepo.go
//
// Generated by this command:
//
//	mockgen -source=jobRepo.go -destination=jobRepo_mock.go -package=repository
//
// Package repository is a generated GoMock package.
package repository
